apiVersion: v1
kind: Pod
metadata:
  name: pod-config 
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: course
      valueFrom:
        ConfigMapKeyRef:
          name: daws-78s
          key: course
    - name: trainer
      valueFrom:
        ConfigMapKeyRef:
          name: daws-78s
          key: trainer        